package com.ycx.webservice_cli;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.9
 * 2016-07-26T11:27:49.606+08:00
 * Generated source version: 3.0.9
 * 
 */
@WebServiceClient(name = "WebServiceSerService", 
                  wsdlLocation = "http://localhost:8080/spring3Maven/cxf/helloTest?wsdl",
                  targetNamespace = "http://webservice.ycx.com/") 
public class WebServiceSerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.ycx.com/", "WebServiceSerService");
    public final static QName WebServiceSerPort = new QName("http://webservice.ycx.com/", "WebServiceSerPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/spring3Maven/cxf/helloTest?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WebServiceSerService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/spring3Maven/cxf/helloTest?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WebServiceSerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebServiceSerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceSerService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WebServiceSerService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WebServiceSerService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WebServiceSerService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns WebServiceSer
     */
    @WebEndpoint(name = "WebServiceSerPort")
    public WebServiceSer getWebServiceSerPort() {
        return super.getPort(WebServiceSerPort, WebServiceSer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceSer
     */
    @WebEndpoint(name = "WebServiceSerPort")
    public WebServiceSer getWebServiceSerPort(WebServiceFeature... features) {
        return super.getPort(WebServiceSerPort, WebServiceSer.class, features);
    }

}
