package com.ycx.webservice_cli;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.9
 * 2016-07-26T11:27:49.550+08:00
 * Generated source version: 3.0.9
 * 
 */
@WebService(targetNamespace = "http://webservice.ycx.com/", name = "WebServiceSer")
@XmlSeeAlso({ObjectFactory.class})
public interface WebServiceSer {

    @WebMethod(operationName = "Hello")
    @RequestWrapper(localName = "Hello", targetNamespace = "http://webservice.ycx.com/", className = "com.ycx.webservice_cli.Hello")
    @ResponseWrapper(localName = "HelloResponse", targetNamespace = "http://webservice.ycx.com/", className = "com.ycx.webservice_cli.HelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String hello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
